### ISSUE TITLE
How to run the app?

### ISSUE THREAD

**Issue by Kudoo39** [Andy-Cuong/Android-Lemonade#1]
I just found this could be an interesting app but I have no idea to run it.

**Comment by Andy-Cuong** [comment]
This is still in production phase, thus not published and downloadable yet. If you want, you can download Android Studio and open this repo inside it, then [set up](https://www.makeuseof.com/tag/what-is-usb-debugging-mode-on-android-makeuseof-explains/) and connect your phone to run the app. But believe me, you won't want to go through such a hassle. (I'll have to learn how to publish an app on Play Store or through apk later...)
